// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"

import "vendor"
import "Chart"
import "progressbar"
import "jquery-jvectormap"
import "jquery-jvectormap-world-mill-en"
import "owl.carousel"
import "off-canvas"
import "hoverable-collapse"
import "misc"
import "settings"
import "todolist"
import "dashboard"
